window.esdocSearchIndex = [
  [
    "aureooms-js-red-black-tree/src/color/black.js~black",
    "variable/index.html#static-variable-BLACK",
    "<span>BLACK</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/color/BLACK.js</span>",
    "variable"
  ],
  [
    "aureooms-js-red-black-tree/src/adt/leaf.js~leaf",
    "function/index.html#static-function-Leaf",
    "<span>Leaf</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/adt/Leaf.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/adt/node.js~node",
    "function/index.html#static-function-Node",
    "<span>Node</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/adt/Node.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/color/red.js~red",
    "variable/index.html#static-variable-RED",
    "<span>RED</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/color/RED.js</span>",
    "variable"
  ],
  [
    "aureooms-js-red-black-tree/src/adt/redblacktree.js~redblacktree",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html",
    "<span>RedBlackTree</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/adt/RedBlackTree.js</span>",
    "class"
  ],
  [
    "aureooms-js-red-black-tree/src/debug/debug.js~debug",
    "function/index.html#static-function-debug",
    "<span>debug</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/debug/debug.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/deletion/delete_case1.js~delete_case1",
    "function/index.html#static-function-delete_case1",
    "<span>delete_case1</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/deletion/delete_case1.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/deletion/delete_case2.js~delete_case2",
    "function/index.html#static-function-delete_case2",
    "<span>delete_case2</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/deletion/delete_case2.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/deletion/delete_case3.js~delete_case3",
    "function/index.html#static-function-delete_case3",
    "<span>delete_case3</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/deletion/delete_case3.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/deletion/delete_case4.js~delete_case4",
    "function/index.html#static-function-delete_case4",
    "<span>delete_case4</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/deletion/delete_case4.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/deletion/delete_case5.js~delete_case5",
    "function/index.html#static-function-delete_case5",
    "<span>delete_case5</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/deletion/delete_case5.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/deletion/delete_case6.js~delete_case6",
    "function/index.html#static-function-delete_case6",
    "<span>delete_case6</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/deletion/delete_case6.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/deletion/delete_one_child.js~delete_one_child",
    "function/index.html#static-function-delete_one_child",
    "<span>delete_one_child</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/deletion/delete_one_child.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/family/grandparent.js~grandparent",
    "function/index.html#static-function-grandparent",
    "<span>grandparent</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/family/grandparent.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/traversal/inordertraversal.js~inordertraversal",
    "function/index.html#static-function-inordertraversal",
    "<span>inordertraversal</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/traversal/inordertraversal.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/insertion/insert.js~insert",
    "function/index.html#static-function-insert",
    "<span>insert</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/insertion/insert.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/insertion/insert_case1.js~insert_case1",
    "function/index.html#static-function-insert_case1",
    "<span>insert_case1</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/insertion/insert_case1.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/insertion/insert_case2.js~insert_case2",
    "function/index.html#static-function-insert_case2",
    "<span>insert_case2</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/insertion/insert_case2.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/insertion/insert_case3.js~insert_case3",
    "function/index.html#static-function-insert_case3",
    "<span>insert_case3</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/insertion/insert_case3.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/insertion/insert_case4.js~insert_case4",
    "function/index.html#static-function-insert_case4",
    "<span>insert_case4</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/insertion/insert_case4.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/insertion/insert_case5.js~insert_case5",
    "function/index.html#static-function-insert_case5",
    "<span>insert_case5</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/insertion/insert_case5.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/family/predecessor.js~predecessor",
    "function/index.html#static-function-predecessor",
    "<span>predecessor</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/family/predecessor.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/traversal/rangetraversal.js~rangetraversal",
    "function/index.html#static-function-rangetraversal",
    "<span>rangetraversal</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/traversal/rangetraversal.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/deletion/replace_node.js~replace_node",
    "function/index.html#static-function-replace_node",
    "<span>replace_node</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/deletion/replace_node.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/rotate/rotate_left.js~rotate_left",
    "function/index.html#static-function-rotate_left",
    "<span>rotate_left</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/rotate/rotate_left.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/rotate/rotate_right.js~rotate_right",
    "function/index.html#static-function-rotate_right",
    "<span>rotate_right</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/rotate/rotate_right.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/search/search.js~search",
    "function/index.html#static-function-search",
    "<span>search</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/search/search.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/family/sibling.js~sibling",
    "function/index.html#static-function-sibling",
    "<span>sibling</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/family/sibling.js</span>",
    "function"
  ],
  [
    "aureooms-js-red-black-tree/src/family/uncle.js~uncle",
    "function/index.html#static-function-uncle",
    "<span>uncle</span> <span class=\"search-result-import-path\">aureooms-js-red-black-tree/src/family/uncle.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/adt/leaf.js",
    "file/src/adt/Leaf.js.html",
    "src/adt/Leaf.js",
    "file"
  ],
  [
    "src/adt/node.js",
    "file/src/adt/Node.js.html",
    "src/adt/Node.js",
    "file"
  ],
  [
    "src/adt/redblacktree.js",
    "file/src/adt/RedBlackTree.js.html",
    "src/adt/RedBlackTree.js",
    "file"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#[symbol.iterator]",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-[Symbol.iterator]",
    "src/adt/RedBlackTree.js~RedBlackTree#[Symbol.iterator]",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#_delete",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-_delete",
    "src/adt/RedBlackTree.js~RedBlackTree#_delete",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#_search",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-_search",
    "src/adt/RedBlackTree.js~RedBlackTree#_search",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#add",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-add",
    "src/adt/RedBlackTree.js~RedBlackTree#add",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#compare",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-member-compare",
    "src/adt/RedBlackTree.js~RedBlackTree#compare",
    "member"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#constructor",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-constructor-constructor",
    "src/adt/RedBlackTree.js~RedBlackTree#constructor",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#get",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-get",
    "src/adt/RedBlackTree.js~RedBlackTree#get",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#has",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-has",
    "src/adt/RedBlackTree.js~RedBlackTree#has",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#items",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-items",
    "src/adt/RedBlackTree.js~RedBlackTree#items",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#range",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-range",
    "src/adt/RedBlackTree.js~RedBlackTree#range",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#remove",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-remove",
    "src/adt/RedBlackTree.js~RedBlackTree#remove",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#root",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-member-root",
    "src/adt/RedBlackTree.js~RedBlackTree#root",
    "member"
  ],
  [
    "src/adt/redblacktree.js~redblacktree.from",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#static-method-from",
    "src/adt/RedBlackTree.js~RedBlackTree.from",
    "method"
  ],
  [
    "src/adt/index.js",
    "file/src/adt/index.js.html",
    "src/adt/index.js",
    "file"
  ],
  [
    "src/color/black.js",
    "file/src/color/BLACK.js.html",
    "src/color/BLACK.js",
    "file"
  ],
  [
    "src/color/red.js",
    "file/src/color/RED.js.html",
    "src/color/RED.js",
    "file"
  ],
  [
    "src/color/index.js",
    "file/src/color/index.js.html",
    "src/color/index.js",
    "file"
  ],
  [
    "src/debug/debug.js",
    "file/src/debug/debug.js.html",
    "src/debug/debug.js",
    "file"
  ],
  [
    "src/debug/index.js",
    "file/src/debug/index.js.html",
    "src/debug/index.js",
    "file"
  ],
  [
    "src/deletion/delete_case1.js",
    "file/src/deletion/delete_case1.js.html",
    "src/deletion/delete_case1.js",
    "file"
  ],
  [
    "src/deletion/delete_case2.js",
    "file/src/deletion/delete_case2.js.html",
    "src/deletion/delete_case2.js",
    "file"
  ],
  [
    "src/deletion/delete_case3.js",
    "file/src/deletion/delete_case3.js.html",
    "src/deletion/delete_case3.js",
    "file"
  ],
  [
    "src/deletion/delete_case4.js",
    "file/src/deletion/delete_case4.js.html",
    "src/deletion/delete_case4.js",
    "file"
  ],
  [
    "src/deletion/delete_case5.js",
    "file/src/deletion/delete_case5.js.html",
    "src/deletion/delete_case5.js",
    "file"
  ],
  [
    "src/deletion/delete_case6.js",
    "file/src/deletion/delete_case6.js.html",
    "src/deletion/delete_case6.js",
    "file"
  ],
  [
    "src/deletion/delete_one_child.js",
    "file/src/deletion/delete_one_child.js.html",
    "src/deletion/delete_one_child.js",
    "file"
  ],
  [
    "src/deletion/index.js",
    "file/src/deletion/index.js.html",
    "src/deletion/index.js",
    "file"
  ],
  [
    "src/deletion/replace_node.js",
    "file/src/deletion/replace_node.js.html",
    "src/deletion/replace_node.js",
    "file"
  ],
  [
    "src/family/grandparent.js",
    "file/src/family/grandparent.js.html",
    "src/family/grandparent.js",
    "file"
  ],
  [
    "src/family/index.js",
    "file/src/family/index.js.html",
    "src/family/index.js",
    "file"
  ],
  [
    "src/family/predecessor.js",
    "file/src/family/predecessor.js.html",
    "src/family/predecessor.js",
    "file"
  ],
  [
    "src/family/sibling.js",
    "file/src/family/sibling.js.html",
    "src/family/sibling.js",
    "file"
  ],
  [
    "src/family/uncle.js",
    "file/src/family/uncle.js.html",
    "src/family/uncle.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/insertion/index.js",
    "file/src/insertion/index.js.html",
    "src/insertion/index.js",
    "file"
  ],
  [
    "src/insertion/insert.js",
    "file/src/insertion/insert.js.html",
    "src/insertion/insert.js",
    "file"
  ],
  [
    "src/insertion/insert_case1.js",
    "file/src/insertion/insert_case1.js.html",
    "src/insertion/insert_case1.js",
    "file"
  ],
  [
    "src/insertion/insert_case2.js",
    "file/src/insertion/insert_case2.js.html",
    "src/insertion/insert_case2.js",
    "file"
  ],
  [
    "src/insertion/insert_case3.js",
    "file/src/insertion/insert_case3.js.html",
    "src/insertion/insert_case3.js",
    "file"
  ],
  [
    "src/insertion/insert_case4.js",
    "file/src/insertion/insert_case4.js.html",
    "src/insertion/insert_case4.js",
    "file"
  ],
  [
    "src/insertion/insert_case5.js",
    "file/src/insertion/insert_case5.js.html",
    "src/insertion/insert_case5.js",
    "file"
  ],
  [
    "src/rotate/index.js",
    "file/src/rotate/index.js.html",
    "src/rotate/index.js",
    "file"
  ],
  [
    "src/rotate/rotate_left.js",
    "file/src/rotate/rotate_left.js.html",
    "src/rotate/rotate_left.js",
    "file"
  ],
  [
    "src/rotate/rotate_right.js",
    "file/src/rotate/rotate_right.js.html",
    "src/rotate/rotate_right.js",
    "file"
  ],
  [
    "src/search/index.js",
    "file/src/search/index.js.html",
    "src/search/index.js",
    "file"
  ],
  [
    "src/search/search.js",
    "file/src/search/search.js.html",
    "src/search/search.js",
    "file"
  ],
  [
    "src/traversal/index.js",
    "file/src/traversal/index.js.html",
    "src/traversal/index.js",
    "file"
  ],
  [
    "src/traversal/inordertraversal.js",
    "file/src/traversal/inordertraversal.js.html",
    "src/traversal/inordertraversal.js",
    "file"
  ],
  [
    "src/traversal/rangetraversal.js",
    "file/src/traversal/rangetraversal.js.html",
    "src/traversal/rangetraversal.js",
    "file"
  ]
]