window.esdocSearchIndex = [
  [
    "aureooms-es-red-black-tree/src/base/colors.js~black",
    "variable/index.html#static-variable-BLACK",
    "<span>BLACK</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/colors.js</span>",
    "variable"
  ],
  [
    "aureooms-es-red-black-tree/src/node/leaf.js~leaf",
    "function/index.html#static-function-Leaf",
    "<span>Leaf</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/node/Leaf.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/node/node.js~node",
    "function/index.html#static-function-Node",
    "<span>Node</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/node/Node.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/base/colors.js~red",
    "variable/index.html#static-variable-RED",
    "<span>RED</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/colors.js</span>",
    "variable"
  ],
  [
    "aureooms-es-red-black-tree/src/adt/redblacktree.js~redblacktree",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html",
    "<span>RedBlackTree</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/adt/RedBlackTree.js</span>",
    "class"
  ],
  [
    "aureooms-es-red-black-tree/src/base/debug.js~debug",
    "function/index.html#static-function-debug",
    "<span>debug</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/debug.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/removal/delete_case1.js~delete_case1",
    "function/index.html#static-function-delete_case1",
    "<span>delete_case1</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/removal/delete_case1.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/removal/delete_case2.js~delete_case2",
    "function/index.html#static-function-delete_case2",
    "<span>delete_case2</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/removal/delete_case2.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/removal/delete_case3.js~delete_case3",
    "function/index.html#static-function-delete_case3",
    "<span>delete_case3</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/removal/delete_case3.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/removal/delete_case4.js~delete_case4",
    "function/index.html#static-function-delete_case4",
    "<span>delete_case4</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/removal/delete_case4.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/removal/delete_case5.js~delete_case5",
    "function/index.html#static-function-delete_case5",
    "<span>delete_case5</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/removal/delete_case5.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/removal/delete_case6.js~delete_case6",
    "function/index.html#static-function-delete_case6",
    "<span>delete_case6</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/removal/delete_case6.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/removal/delete_one_child.js~delete_one_child",
    "function/index.html#static-function-delete_one_child",
    "<span>delete_one_child</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/removal/delete_one_child.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/base/find.js~find",
    "function/index.html#static-function-find",
    "<span>find</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/find.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/family/grandparent.js~grandparent",
    "function/index.html#static-function-grandparent",
    "<span>grandparent</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/family/grandparent.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/base/inordertraversal.js~inordertraversal",
    "function/index.html#static-function-inordertraversal",
    "<span>inordertraversal</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/inordertraversal.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/base/insert.js~insert",
    "function/index.html#static-function-insert",
    "<span>insert</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/insert.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/insertion/insert_case1.js~insert_case1",
    "function/index.html#static-function-insert_case1",
    "<span>insert_case1</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/insertion/insert_case1.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/insertion/insert_case2.js~insert_case2",
    "function/index.html#static-function-insert_case2",
    "<span>insert_case2</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/insertion/insert_case2.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/insertion/insert_case3.js~insert_case3",
    "function/index.html#static-function-insert_case3",
    "<span>insert_case3</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/insertion/insert_case3.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/insertion/insert_case4.js~insert_case4",
    "function/index.html#static-function-insert_case4",
    "<span>insert_case4</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/insertion/insert_case4.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/insertion/insert_case5.js~insert_case5",
    "function/index.html#static-function-insert_case5",
    "<span>insert_case5</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/insertion/insert_case5.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/family/predecessor.js~predecessor",
    "function/index.html#static-function-predecessor",
    "<span>predecessor</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/family/predecessor.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/base/replace_node.js~replace_node",
    "function/index.html#static-function-replace_node",
    "<span>replace_node</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/replace_node.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/base/rotate_left.js~rotate_left",
    "function/index.html#static-function-rotate_left",
    "<span>rotate_left</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/rotate_left.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/base/rotate_right.js~rotate_right",
    "function/index.html#static-function-rotate_right",
    "<span>rotate_right</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/base/rotate_right.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/family/sibling.js~sibling",
    "function/index.html#static-function-sibling",
    "<span>sibling</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/family/sibling.js</span>",
    "function"
  ],
  [
    "aureooms-es-red-black-tree/src/family/uncle.js~uncle",
    "function/index.html#static-function-uncle",
    "<span>uncle</span> <span class=\"search-result-import-path\">aureooms-es-red-black-tree/src/family/uncle.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/adt/redblacktree.js",
    "file/src/adt/RedBlackTree.js.html",
    "src/adt/RedBlackTree.js",
    "file"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#[symbol.iterator]",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-[Symbol.iterator]",
    "src/adt/RedBlackTree.js~RedBlackTree#[Symbol.iterator]",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#add",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-add",
    "src/adt/RedBlackTree.js~RedBlackTree#add",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#compare",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-member-compare",
    "src/adt/RedBlackTree.js~RedBlackTree#compare",
    "member"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#constructor",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-constructor-constructor",
    "src/adt/RedBlackTree.js~RedBlackTree#constructor",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#delete",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-delete",
    "src/adt/RedBlackTree.js~RedBlackTree#delete",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#find",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-method-find",
    "src/adt/RedBlackTree.js~RedBlackTree#find",
    "method"
  ],
  [
    "src/adt/redblacktree.js~redblacktree#root",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#instance-member-root",
    "src/adt/RedBlackTree.js~RedBlackTree#root",
    "member"
  ],
  [
    "src/adt/redblacktree.js~redblacktree.from",
    "class/src/adt/RedBlackTree.js~RedBlackTree.html#static-method-from",
    "src/adt/RedBlackTree.js~RedBlackTree.from",
    "method"
  ],
  [
    "src/adt/index.js",
    "file/src/adt/index.js.html",
    "src/adt/index.js",
    "file"
  ],
  [
    "src/base/colors.js",
    "file/src/base/colors.js.html",
    "src/base/colors.js",
    "file"
  ],
  [
    "src/base/debug.js",
    "file/src/base/debug.js.html",
    "src/base/debug.js",
    "file"
  ],
  [
    "src/base/find.js",
    "file/src/base/find.js.html",
    "src/base/find.js",
    "file"
  ],
  [
    "src/base/index.js",
    "file/src/base/index.js.html",
    "src/base/index.js",
    "file"
  ],
  [
    "src/base/inordertraversal.js",
    "file/src/base/inordertraversal.js.html",
    "src/base/inordertraversal.js",
    "file"
  ],
  [
    "src/base/insert.js",
    "file/src/base/insert.js.html",
    "src/base/insert.js",
    "file"
  ],
  [
    "src/base/replace_node.js",
    "file/src/base/replace_node.js.html",
    "src/base/replace_node.js",
    "file"
  ],
  [
    "src/base/rotate_left.js",
    "file/src/base/rotate_left.js.html",
    "src/base/rotate_left.js",
    "file"
  ],
  [
    "src/base/rotate_right.js",
    "file/src/base/rotate_right.js.html",
    "src/base/rotate_right.js",
    "file"
  ],
  [
    "src/family/grandparent.js",
    "file/src/family/grandparent.js.html",
    "src/family/grandparent.js",
    "file"
  ],
  [
    "src/family/index.js",
    "file/src/family/index.js.html",
    "src/family/index.js",
    "file"
  ],
  [
    "src/family/predecessor.js",
    "file/src/family/predecessor.js.html",
    "src/family/predecessor.js",
    "file"
  ],
  [
    "src/family/sibling.js",
    "file/src/family/sibling.js.html",
    "src/family/sibling.js",
    "file"
  ],
  [
    "src/family/uncle.js",
    "file/src/family/uncle.js.html",
    "src/family/uncle.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/insertion/index.js",
    "file/src/insertion/index.js.html",
    "src/insertion/index.js",
    "file"
  ],
  [
    "src/insertion/insert_case1.js",
    "file/src/insertion/insert_case1.js.html",
    "src/insertion/insert_case1.js",
    "file"
  ],
  [
    "src/insertion/insert_case2.js",
    "file/src/insertion/insert_case2.js.html",
    "src/insertion/insert_case2.js",
    "file"
  ],
  [
    "src/insertion/insert_case3.js",
    "file/src/insertion/insert_case3.js.html",
    "src/insertion/insert_case3.js",
    "file"
  ],
  [
    "src/insertion/insert_case4.js",
    "file/src/insertion/insert_case4.js.html",
    "src/insertion/insert_case4.js",
    "file"
  ],
  [
    "src/insertion/insert_case5.js",
    "file/src/insertion/insert_case5.js.html",
    "src/insertion/insert_case5.js",
    "file"
  ],
  [
    "src/node/leaf.js",
    "file/src/node/Leaf.js.html",
    "src/node/Leaf.js",
    "file"
  ],
  [
    "src/node/node.js",
    "file/src/node/Node.js.html",
    "src/node/Node.js",
    "file"
  ],
  [
    "src/node/index.js",
    "file/src/node/index.js.html",
    "src/node/index.js",
    "file"
  ],
  [
    "src/removal/delete_case1.js",
    "file/src/removal/delete_case1.js.html",
    "src/removal/delete_case1.js",
    "file"
  ],
  [
    "src/removal/delete_case2.js",
    "file/src/removal/delete_case2.js.html",
    "src/removal/delete_case2.js",
    "file"
  ],
  [
    "src/removal/delete_case3.js",
    "file/src/removal/delete_case3.js.html",
    "src/removal/delete_case3.js",
    "file"
  ],
  [
    "src/removal/delete_case4.js",
    "file/src/removal/delete_case4.js.html",
    "src/removal/delete_case4.js",
    "file"
  ],
  [
    "src/removal/delete_case5.js",
    "file/src/removal/delete_case5.js.html",
    "src/removal/delete_case5.js",
    "file"
  ],
  [
    "src/removal/delete_case6.js",
    "file/src/removal/delete_case6.js.html",
    "src/removal/delete_case6.js",
    "file"
  ],
  [
    "src/removal/delete_one_child.js",
    "file/src/removal/delete_one_child.js.html",
    "src/removal/delete_one_child.js",
    "file"
  ],
  [
    "src/removal/index.js",
    "file/src/removal/index.js.html",
    "src/removal/index.js",
    "file"
  ]
]